# Numpy basics

In [1]:
import numpy as np

the basics

In [2]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [4]:
#get dimension
b.ndim

2

In [5]:
a.shape

(3,)

In [6]:
#get type #int32 is default
a.dtype

dtype('int32')

In [7]:
a=np.array([1,2,3],dtype='int16')
a.dtype

dtype('int16')

In [8]:
#get size
a.itemsize

2

In [9]:
a.size

3

In [10]:
# get total size
a.nbytes   
    #or
a.size*a.itemsize

6

In [11]:
#floats are bigger than integers
b.size
b.itemsize
b.nbytes

48

# accessing/changing specific elements, rows ,columns etc

In [12]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [13]:
a.shape

(2, 7)

In [14]:
#get a specific element [r,c]
a[0,5]
  #or
a[0,-2]

6

In [15]:
# get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
#get a specific column
a[:,3]

array([ 4, 11])

In [17]:
#getting a little more  fancy [startindex:endindex:stepsize]
a[0,1:7:2]


array([2, 4, 6])

In [18]:
a[0,3]=90
a

array([[ 1,  2,  3, 90,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [19]:
a

array([[ 1,  2,  3, 90,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [20]:
a[:,2]=5
a
a[:,2]=[1,2]
a

array([[ 1,  2,  1, 90,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 13, 14]])

# 3D example

In [21]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [22]:
#get specific element (work outside in)
b[0,1,1]

4

In [23]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [24]:
b[:,:,0]

array([[1, 3],
       [5, 7]])

In [25]:
#replace
b[:,1,:]=[[0,0],[2,8]]
b

array([[[1, 2],
        [0, 0]],

       [[5, 6],
        [2, 8]]])

# initializing diff types of arrays

In [26]:
#all 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [29]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [30]:
#all is matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [31]:
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [32]:
#any other num
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [33]:
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [34]:
#any other num (full_like)
np.full_like(a,5)

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [35]:
#random decimal numbers
np.random.rand(4,2)

array([[0.77667972, 0.17323841],
       [0.45552342, 0.53907666],
       [0.91892063, 0.79123429],
       [0.74282754, 0.09781729]])

In [36]:
np.random.rand(4,2,2)

array([[[0.35861179, 0.29705648],
        [0.8510909 , 0.40272147]],

       [[0.47476527, 0.78621876],
        [0.334794  , 0.98112287]],

       [[0.79753545, 0.18202623],
        [0.2203874 , 0.57022567]],

       [[0.1734022 , 0.2499887 ],
        [0.821867  , 0.39257174]]])

In [37]:
np.random.random_sample(a.shape)

array([[0.583774  , 0.48821599, 0.9225157 , 0.59760826, 0.46747204,
        0.85778049, 0.25285443],
       [0.79788453, 0.11386364, 0.98955168, 0.33998006, 0.47204574,
        0.76552932, 0.94755109]])

In [38]:
#random integer values
np.random.randint(7,size=(3,3))

array([[5, 0, 6],
       [4, 0, 4],
       [1, 2, 0]])

In [39]:
np.random.randint(3,7,size=(3,3))

array([[6, 5, 4],
       [3, 3, 6],
       [6, 6, 5]])

In [40]:
np.random.randint(-3,7,size=(3,3))

array([[-3,  1, -2],
       [ 2, -2,  0],
       [ 2,  6,  2]])

In [41]:
#the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
#repeat an  array
arr=np.array([1,2,3])
r1=np.repeat(arr,3,axis=0)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [43]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

proplem #1

In [44]:
ones=np.ones((5,5))
print(ones)

zeros=np.zeros((3,3))
print(zeros)
zeros[1,1]=9
print(zeros)
ones[1:4,1:4]=zeros
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# be carefull when copyiny arrays

In [45]:
w=np.array([2,3,5])
print(w)
d=np.array([5,7,9])
print(d)
d=w
d[0]=466
print(d)
print('____________')
print(w)
print('____________')


d=w.copy()# use this comment while copying the arrays so it wont
          # change the value in original array  
d[0]=1234
print(d)
print('___________')
print(w)

[2 3 5]
[5 7 9]
[466   3   5]
____________
[466   3   5]
____________
[1234    3    5]
___________
[466   3   5]


# mathematics

In [46]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [47]:
a+2

array([3, 4, 5, 6])

In [48]:
a-2

array([-1,  0,  1,  2])

In [49]:
a*2

array([2, 4, 6, 8])

In [50]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [51]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [52]:
b=np.array([1,1,1,1])
a+b

array([2, 3, 4, 5])

In [53]:
#take the sin
np.sin(a)
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [54]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

# linear algebra

In [55]:
a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [56]:
b=np.full((3,2),2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [57]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [58]:
#find the determinant
c=np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [59]:
n=np.array([[1,7,3],[1,2,3],[1,2,4]])
np.linalg.det(n)

-4.999999999999999

In [60]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

# statistics

In [61]:
stats=np.array([[2,3,1],[1,5,6]])
stats

array([[2, 3, 1],
       [1, 5, 6]])

In [62]:
np.min(stats)

1

In [63]:
np.min(stats,axis=1) #axis command gives the min of the first row and second row
                     #axis=1(rows)  axis=(0)columns

array([1, 1])

In [64]:
np.min(stats,axis=0)

array([1, 3, 1])

In [65]:
np.max(stats)

6

In [66]:
np.max(stats,axis=1)

array([3, 6])

In [67]:
np.max(stats,axis=0)

array([2, 5, 6])

In [68]:
np.sum(stats)

18

In [69]:
np.sum(stats,axis=1)

array([ 6, 12])

In [70]:
np.sum(stats,axis=0)

array([3, 8, 7])

# reorganizing arrays

In [71]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print('--------')
print(before.shape)
print('--------')

after=before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
--------
(2, 4)
--------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [72]:
#vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2])
np.vstack([v1,v2,v2,v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [73]:
#horizontal stack

In [74]:
h1=np.ones((2,4))
print(h1)
print('----------')
h2=np.zeros((2,2))
print(h2)
print('---------')

np.hstack([h1,h2])

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
----------
[[0. 0.]
 [0. 0.]]
---------


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# miscellaneous
   load data from file

In [75]:
fd= np.genfromtxt('data.txt',delimiter=',')
fd1=fd.astype('int32')
fd1

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

# boolean masking and advanced indexing

In [76]:
fd1>15

array([[False, False,  True, False,  True,  True, False, False,  True,
        False, False, False, False, False, False, False, False, False],
       [False,  True, False,  True,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False,  True,  True, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [77]:
fd1[fd1>40]

array([196,  75,  42, 766,  75,  55, 999,  78,  76,  88])

In [78]:
#you can index with a list in numpy
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,3]]

array([2, 3, 4])

In [79]:
np.any(fd1>50,axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [80]:
np.all(fd1>50,axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [81]:
np.all(fd1>50,axis=1)

array([False, False, False])

In [82]:
((fd1>50 )&( fd1<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [83]:
(~(fd1>50 )&( fd1<100))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [84]:
#problem2
y=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [85]:
y[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [86]:
y[[0,1,2,3,4],[0,1,2,3,4]]

array([ 1,  7, 13, 19, 25])

In [87]:
y[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [88]:
y[[0,3,4],3:]

array([[ 4,  5],
       [19, 20],
       [24, 25]])

# code basics

In [89]:
np.array((1,5))

array([1, 5])

In [90]:
np.arange(1,5)

array([1, 2, 3, 4])

In [91]:
np.arange(1,5,2)

array([1, 3])

In [92]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [93]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [94]:
d=np.arange(1,5)
d

array([1, 2, 3, 4])

In [95]:
d.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [96]:
d.ravel()

array([1, 2, 3, 4])

In [97]:
d

array([1, 2, 3, 4])

In [98]:
np.sqrt(d)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [99]:
np.std(d)

1.118033988749895

In [100]:
a=np.array([[2,3],[2,3]])
print(a)
b=np.array([[4,6],[3,8]])
print(b)
a.dot(b)

[[2 3]
 [2 3]]
[[4 6]
 [3 8]]


array([[17, 36],
       [17, 36]])

In [101]:
s=np.array([[1,2,3],[2,5,6],[5,3,9]])
s

array([[1, 2, 3],
       [2, 5, 6],
       [5, 3, 9]])

In [102]:
for i in s:
    print(i)

[1 2 3]
[2 5 6]
[5 3 9]


In [103]:
for i in s.flat:
    print(i)    

1
2
3
2
5
6
5
3
9


In [104]:
#read row by row
for i in np.nditer(s,order='c'):
    print(i)

1
2
3
2
5
6
5
3
9


In [105]:
#read column by column
for i in np.nditer(s,order='f'):
    print(i)

1
2
5
2
5
3
3
6
9


In [106]:
for i in np.nditer(s,order='f',flags=['external_loop']):
    print(i)

[1 2 5]
[2 5 3]
[3 6 9]


In [107]:
for i in np.nditer(s,op_flags=['readwrite']):
    s[...]=s*s
s

array([[          1,           0,  1995565057],
       [          0,   -59967487,           0],
       [  -59967487,  1995565057, -1876701183]])

In [108]:
t1=np.arange(8).reshape(4,2)
print(t1)
t2=np.arange(6,14).reshape(4,2)
print(t2)
t3=np.arange(3,15,4).reshape(3,1)
print(t3)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[ 6  7]
 [ 8  9]
 [10 11]
 [12 13]]
[[ 3]
 [ 7]
 [11]]


In [109]:
for x,y in np.nditer([t1,t2]):
    print(x,y)

0 6
1 7
2 8
3 9
4 10
5 11
6 12
7 13


In [110]:
np.vstack((t1,t2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13]])

In [111]:
np.hstack((t1,t2))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11],
       [ 6,  7, 12, 13]])

In [112]:
a5=np.arange(0,30).reshape(5,6)
a5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [113]:
np.hsplit(a5,3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29]])]

In [114]:
u=a5>20
u

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [115]:
a5[u]

array([21, 22, 23, 24, 25, 26, 27, 28, 29])

In [116]:
a5[u]=-1
a5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1]])

In [117]:
#readandwrite files in numpy
#np.savetxt('test.txt',a5) ------->to write file
a3=np.loadtxt('test.txt') #------->to read file
a3

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1.]])